### ISSUE TITLE
再使用SpringAI进行function-call时，发生非web上下文报错。我不太理解为何会报这种错。

### ISSUE THREAD

**Issue by LittleDrip** [qifan777/dive-into-spring-ai#4]
具体是这样的的：
在下面代码的 papersService.getEvaluation里有一个 User user = (User) StpUtil.getSession().get("user");。就是这句话报错：是非web上下文。
@bean
@description("做出心理健康评估")
public Function<PapersRequest, String> psychologicalHealthAssessment(){
return request -> {
Result evaluation = papersService.getEvaluation(1);
UserPapersDetailVo data = (UserPapersDetailVo )evaluation.getData();
return data.getEvaluation();
};
}

**Comment by qifan777** [comment]
这个是satoken的问题，如果你是一步执行的就会报这个错误
